//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace nasauncle.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SeaData
    {
        public int id { get; set; }
        public Nullable<System.DateTime> DateX { get; set; }
        public Nullable<decimal> dat { get; set; }
        public Nullable<decimal> lonX { get; set; }
        public Nullable<decimal> chll { get; set; }
        public Nullable<decimal> sst { get; set; }
        public Nullable<decimal> sa { get; set; }
        public Nullable<decimal> cerrentX { get; set; }
        public Nullable<decimal> cerrentY { get; set; }
        public Nullable<decimal> waveh { get; set; }
        public Nullable<decimal> tide { get; set; }
        public Nullable<decimal> uv { get; set; }
    }
}
